### ISSUE TITLE
Failed tests for Pulse 

### ISSUE THREAD

**Issue by MrJoker007** [AlienVault-Labs/OTX-Java-SDK#5]
Hi, I have encounter these two failed test : 
  OtxJavaSdkApplicationTests.testListEvents:144 All events not larger then a subset
  OtxJavaSdkApplicationTests.testSearchPulses:95 Could not find pulse

and also this error Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project DirectConnect-Java-SDK

My Environment : 
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: C:\Users\TMF\Documents\apache-maven-3.3.9\bin..
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: C:\Program Files (x86)\Java\jdk1.8.0_40\jre
Default locale: en_MY, platform encoding: Cp1252
OS name: "windows 8.1", version: "6.3", arch: "x86", family: "dos"

2016-10-21 22:13:20.055  INFO 12040 --- [main] o.a.maven.surefire.booter.ForkedBooter   : Starting ForkedBooter v2.19.1 on LAPTOP-N3KL0FO7 with PID 12040 (C:\Users\TMF.m2\repository\org\apache\maven\surefire\surefire-booter\2.19.1\surefire-booter-2.19.1.jar started by TMF in C:\Users\TMF\Documents\GitHub\AlienVault\OTX-Java-SDK)
2016-10-21 22:13:20.727  INFO 12040 --- [main] o.a.maven.surefire.booter.ForkedBooter   : Started ForkedBooter in 0.858 seconds (JVM running for 1.671)
Tests run: 11, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 138.47 sec <<< FAILURE! - in com.alienvault.otx.OtxJavaSdkApplicationTests
testListEvents(com.alienvault.otx.OtxJavaSdkApplicationTests)  Time elapsed: 2.147 sec  <<< FAILURE!
java.lang.AssertionError: All events not larger then a subset
        at com.alienvault.otx.OtxJavaSdkApplicationTests.testListEvents(OtxJavaSdkApplicationTests.java:144)

testSearchPulses(com.alienvault.otx.OtxJavaSdkApplicationTests)  Time elapsed: 0.513 sec  <<< FAILURE!
java.lang.AssertionError: Could not find pulse
        at com.alienvault.otx.OtxJavaSdkApplicationTests.testSearchPulses(OtxJavaSdkApplicationTests.java:95)

Results :

Failed tests:
  OtxJavaSdkApplicationTests.testListEvents:144 All events not larger then a subset
  OtxJavaSdkApplicationTests.testSearchPulses:95 Could not find pulse

Tests run: 11, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:36 min
[INFO] Finished at: 2016-10-21T22:15:38+08:00
[INFO] Final Memory: 17M/44M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project DirectConnect-Java-SDK: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\TMF\Documents\GitHub\AlienVault\OTX-Java-SDK\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by sossickd** [comment]
I am experiencing the same issue, has anyone found a resolution to this.

Environment:
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.7.0_111, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.111-2.6.7.2.el7_2.x86_64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-327.22.2.el7.x86_64", arch: "amd64", family: "unix"

test_application.properties

VALID_PULSE_NAME=Qarallax RAT: Spying On US Visa Applicants
VALID_USERNAME=AlienVault
VALID_PULSE_ID=5756b9746eb8c60134a9e203
NUMBER_PULSES_RELATED_TO_VALID_PULSE_ID=1

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.alienvault.otx.OtxJavaSdkApplicationTests
10:24:07.528 [main] DEBUG o.s.t.c.j.SpringJUnit4ClassRunner - SpringJUnit4ClassRunner constructor called with [class com.alienvault.otx.OtxJavaSdkApplicationTests].
10:24:07.555 [main] DEBUG o.s.test.context.BootstrapUtils - Instantiating TestContextBootstrapper from class [org.springframework.test.context.support.DefaultTestContextBootstra                                                            pper]
10:24:07.624 [main] DEBUG o.s.t.c.s.DefaultTestContextBootstrapper - Found explicit ContextLoader class [org.springframework.boot.test.SpringApplicationContextLoader] for contex                                                            t configuration attributes [ContextConfigurationAttributes@7186fe17 declaringClass = 'com.alienvault.otx.OtxJavaSdkApplicationTests', classes = '{class com.alienvault.otx.Comman                                                            dlineRunner}', locations = '{}', inheritLocations = true, initializers = '{}', inheritInitializers = true, name = [null], contextLoaderClass = 'org.springframework.boot.test.Spr                                                            ingApplicationContextLoader']
10:24:07.628 [main] DEBUG o.s.t.c.support.ActiveProfilesUtils - Could not find an 'annotation declaring class' for annotation type [org.springframework.test.context.ActiveProfil                                                            es] and class [com.alienvault.otx.OtxJavaSdkApplicationTests]
10:24:07.658 [main] DEBUG o.s.t.c.s.DefaultTestContextBootstrapper - @TestExecutionListeners is not present for class [com.alienvault.otx.OtxJavaSdkApplicationTests]: using defa                                                            ults.
10:24:07.688 [main] INFO  o.s.t.c.s.DefaultTestContextBootstrapper - Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframe                                                            work.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.D                                                            irtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutio                                                            nListener]
10:24:07.709 [main] INFO  o.s.t.c.s.DefaultTestContextBootstrapper - Could not instantiate TestExecutionListener [org.springframework.test.context.transaction.TransactionalTestE                                                            xecutionListener]. Specify custom listener classes or make the default listener classes (and their required dependencies) available. Offending class: [org/springframework/transa                                                            ction/interceptor/TransactionAttributeSource]
10:24:07.710 [main] INFO  o.s.t.c.s.DefaultTestContextBootstrapper - Could not instantiate TestExecutionListener [org.springframework.test.context.jdbc.SqlScriptsTestExecutionLi                                                            stener]. Specify custom listener classes or make the default listener classes (and their required dependencies) available. Offending class: [org/springframework/transaction/inte                                                            rceptor/TransactionAttribute]
10:24:07.711 [main] INFO  o.s.t.c.s.DefaultTestContextBootstrapper - Could not instantiate TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListen                                                            er]. Specify custom listener classes or make the default listener classes (and their required dependencies) available. Offending class: [javax/servlet/ServletContext]
10:24:07.713 [main] INFO  o.s.t.c.s.DefaultTestContextBootstrapper - Using TestExecutionListeners: [org.springframework.test.context.support.DependencyInjectionTestExecutionList                                                            ener@7629a4cb, org.springframework.test.context.support.DirtiesContextTestExecutionListener@28024808]
10:24:07.715 [main] DEBUG o.s.t.annotation.ProfileValueUtils - Retrieved @ProfileValueSourceConfiguration [null] for test class [com.alienvault.otx.OtxJavaSdkApplicationTests]
10:24:07.716 [main] DEBUG o.s.t.annotation.ProfileValueUtils - Retrieved ProfileValueSource type [class org.springframework.test.annotation.SystemProfileValueSource] for class [                                                            com.alienvault.otx.OtxJavaSdkApplicationTests]
10:24:07.717 [main] DEBUG o.s.t.annotation.ProfileValueUtils - Retrieved @ProfileValueSourceConfiguration [null] for test class [com.alienvault.otx.OtxJavaSdkApplicationTests]
10:24:07.717 [main] DEBUG o.s.t.annotation.ProfileValueUtils - Retrieved ProfileValueSource type [class org.springframework.test.annotation.SystemProfileValueSource] for class [                                                            com.alienvault.otx.OtxJavaSdkApplicationTests]
10:24:07.744 [main] DEBUG o.s.t.annotation.ProfileValueUtils - Retrieved @ProfileValueSourceConfiguration [null] for test class [com.alienvault.otx.OtxJavaSdkApplicationTests]
10:24:07.744 [main] DEBUG o.s.t.annotation.ProfileValueUtils - Retrieved ProfileValueSource type [class org.springframework.test.annotation.SystemProfileValueSource] for class [                                                            com.alienvault.otx.OtxJavaSdkApplicationTests]
10:24:07.746 [main] DEBUG o.s.t.c.s.DependencyInjectionTestExecutionListener - Performing dependency injection for test context [[DefaultTestContext@564e4111 testClass = OtxJava                                                            SdkApplicationTests, testInstance = com.alienvault.otx.OtxJavaSdkApplicationTests@2b91ef5b, testMethod = [null], testException = [null], mergedContextConfiguration = [MergedCont                                                            extConfiguration@79f955b5 testClass = OtxJavaSdkApplicationTests, locations = '{}', classes = '{class com.alienvault.otx.CommandlineRunner}', contextInitializerClasses = '[]', a                                                            ctiveProfiles = '{}', propertySourceLocations = '{classpath:test_application.properties}', propertySourceProperties = '{}', contextLoader = 'org.springframework.boot.test.Spring                                                            ApplicationContextLoader', parent = [null]]]].
10:24:07.907 [main] DEBUG o.s.core.env.StandardEnvironment - Adding [systemProperties] PropertySource with lowest search precedence
10:24:07.908 [main] DEBUG o.s.core.env.StandardEnvironment - Adding [systemEnvironment] PropertySource with lowest search precedence
10:24:07.909 [main] DEBUG o.s.core.env.StandardEnvironment - Initialized StandardEnvironment with PropertySources [systemProperties,systemEnvironment]
10:24:07.910 [main] DEBUG o.s.core.env.StandardEnvironment - Adding [integrationTest] PropertySource with search precedence immediately lower than [systemEnvironment]

2016-11-27 10:24:08.247  INFO 28636 --- [           main] o.a.maven.surefire.booter.ForkedBooter   : Starting ForkedBooter v2.17 on iobqhsmont006v.iob.rbxd.ds with PID 28636 (/r                                                            oot/.m2/repository/org/apache/maven/surefire/surefire-booter/2.17/surefire-booter-2.17.jar started by root in /root/OTX-Java-SDK-master)
2016-11-27 10:24:10.327  INFO 28636 --- [           main] o.a.maven.surefire.booter.ForkedBooter   : Started ForkedBooter in 2.414 seconds (JVM running for 3.395)
Tests run: 11, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 163.284 sec <<< FAILURE! - in com.alienvault.otx.OtxJavaSdkApplicationTests
testListEvents(com.alienvault.otx.OtxJavaSdkApplicationTests)  Time elapsed: 2.103 sec  <<< FAILURE!
java.lang.AssertionError: All events not larger then a subset
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at com.alienvault.otx.OtxJavaSdkApplicationTests.testListEvents(OtxJavaSdkApplicationTests.java:144)

testSearchPulses(com.alienvault.otx.OtxJavaSdkApplicationTests)  Time elapsed: 1.164 sec  <<< FAILURE!
java.lang.AssertionError: Could not find pulse
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at com.alienvault.otx.OtxJavaSdkApplicationTests.testSearchPulses(OtxJavaSdkApplicationTests.java:95)


Results :

Failed tests:
  OtxJavaSdkApplicationTests.testListEvents:144 All events not larger then a subset
  OtxJavaSdkApplicationTests.testSearchPulses:95 Could not find pulse

Tests run: 11, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:48 min
[INFO] Finished at: 2016-11-27T10:26:50+00:00
[INFO] Final Memory: 12M/29M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project DirectConnect-Java-SDK: There are test failures.
[ERROR]
[ERROR] Please refer to /root/OTX-Java-SDK-master/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project DirectConnect-J                                                            ava-SDK: There are test failures.

Please refer to /root/OTX-Java-SDK-master/target/surefire-reports for the individual test results.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /root/OTX-Java-SDK-master/target/surefire-reports for the individual test results.
        at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:82)
        at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:195)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:861)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:729)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
